### ISSUE TITLE
keras depend tensorflow module

### ISSUE THREAD

**Issue by ipsec** [che-shr-cat/alphago#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/fernando/Desenvolvimento/Projetos/alphago/alphago-zero.py", line 3, in <module>
    import keras
  File "/Users/fernando/Desenvolvimento/VirtualEnvs/MCTS/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/fernando/Desenvolvimento/VirtualEnvs/MCTS/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/Users/fernando/Desenvolvimento/VirtualEnvs/MCTS/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/Users/fernando/Desenvolvimento/VirtualEnvs/MCTS/lib/python3.6/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/Users/fernando/Desenvolvimento/VirtualEnvs/MCTS/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

tensorflow is requirement to run your code
please update documentation

**Comment by che-shr-cat** [comment]
Hi,
Keras actually works with different backends, Tensorflow is just a one (yet most known). 
I think these models do not use any features specific to Tensorflow.
